### ISSUE TITLE
Outdated AppImageKit

### ISSUE THREAD

**Issue by probonopd** [mrbitt/mrbit-overlay#2]
https://github.com/mrbitt/mrbit-overlay/blob/6e56544215ce4119220f0c9b0dd40153fcccae32/sys-fs/AppImageKit/AppImageKit-9999.ebuild is using an outdated branch of AppImageKit, the current one is `appimagetool/master`. 

AppImageAssistant, AppDirAssistant, and AppImageExtract have been replaced by `appimagetool` and the optional `appimaged` daemon.

Sorry for the inconvenience caused by this.

**Comment by mrbitt** [comment]
Sorry, I don't know why but I didn't notice this issue, but I updated the ebuild.
Thanks for reporting this issue :)
